[package]
name = "sos"
version = "0.0.0"
authors = ["Arbel Israeli <arbel03@gmail.com>"]
exclude = ["src/arch/*.asm", "filesystem/*"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
spin = "0.4.5"
bitmap_allocator = { path = "bitmap_allocator" }